internal static class BuiltInLang {
    public static string Get(string lang) => lang switch {
        "de" => """
{
  "btn.save":               "✓ Speichern",
  "btn.cancel":             "✕ Abbrechen",
  "btn.commit":             "✓ Bump & Commit",
  "btn.block_commit":       "✗ Commit stoppen",
  "btn.bypass_hook":        "↷ Commit ohne Bump",
  "btn.yes":                "Ja",
  "btn.no":                 "Nein",
  "toolbar.settings":       "Einstellungen",
  "toolbar.load_settings":  "Einstellungen öffnen…",
  "toolbar.load_browse":    "Öffnen…",
  "toolbar.info":           "Über",
  "toolbar.add_project":     "Zu Settings hinzufügen",
  "toolbar.add_project_tip": "Dieses Projekt zur aktiven settings.json hinzufügen",
  "toolbar.add_project_ok":  "Projekt zur settings.json hinzugefügt.",
  "toolbar.sync_versions":   "Auf höchste sync.",
  "toolbar.sync_versions_tip": "Alle sichtbaren Projekte auf die höchste Version unter ihnen setzen",
  "settings.title":         "Einstellungen",
  "settings.body":          "settings.json wurde im Editor geöffnet.\n\nNach dem Speichern OK drücken, um die Einstellungen neu zu laden.",
  "info.title":             "Über VerBump",
  "info.language":          "Sprache: {0}",
  "info.description":       "Versionsdatei-Manager für Windows-Entwickler.\nFree & open source — MIT-Lizenz.",
  "info.sponsor":           "\u2764  Dieses Projekt auf GitHub sponsern",
  "info.report":            "\u2709  Problem melden",
  "info.source":            "\u2325  Quellcode auf GitHub",
  "settings.created":       "settings.json erstellt: {0}\nBitte Pfade eintragen.",
  "error.json":             "JSON Fehler: {0}",
  "error.save":             "Fehler beim Speichern: {0}",
  "error.nofiles":          "Keine VERSION-Dateien gefunden.\nEinstellungen-Datei: {0}\n\nEinstellungen bearbeiten?",
  "error.bump_unavailable": "⚠ Strg+{0} nicht verfügbar für Schema \"{1}\"",
  "status.scheme":          "Schema: {0}",
  "status.shortcut":        "Strg+{0}={1}",
  "status.backup_on":       "Backup: [X]",
  "status.backup_off":      "Backup: [ ]",
  "status.ok":              "VERSION ist aktuell.",
  "project.unnamed":        "Unbenannt",
  "editor.title":           "Editor wählen",
  "editor.prompt":          "Befehl oder Pfad zum Editor (z. B. code, notepad++, gedit):",
  "editor.error":           "Editor konnte nicht gestartet werden: {0}",
  "menu.file":              "Datei",
  "menu.edit_settings":     "Einstellungen",
  "menu.load_settings":     "Settings-Datei \u00f6ffnen",
  "menu.load_version":      "VERSION \u00f6ffnen",
  "menu.exit":              "Beenden",
  "menu.edit":              "Bearbeiten",
  "menu.undo":              "R\u00fckg\u00e4ngig",
  "menu.view":              "Ansicht",
  "menu.show_stale":        "Veraltete anzeigen",
  "menu.show_current":      "Aktuelle anzeigen",
  "menu.about":             "\u00dcber VerBump",
  "menu.add_favorite":      "\u2605 Als Favorit speichern",
  "menu.remove_favorite":   "(\u2715) Aus Favoriten entfernen",
  "menu.add_version_fav":   "\u2605 Zu VERSION-Favoriten hinzufügen",
  "menu.remove_version_fav":"(\u2715) Aus VERSION-Favoriten entfernen"
}

""",
        "en" => """
{
  "btn.save":               "✓ Save",
  "btn.cancel":             "✕ Cancel",
  "btn.commit":             "✓ Bump & Commit",
  "btn.block_commit":       "✗ Block Commit",
  "btn.bypass_hook":        "↷ Skip This Time",
  "btn.yes":                "Yes",
  "btn.no":                 "No",
  "toolbar.settings":       "Settings",
  "toolbar.load_settings":  "Open settings…",
  "toolbar.load_browse":    "Open…",
  "toolbar.info":           "About",
  "toolbar.add_project":     "Add to settings",
  "toolbar.add_project_tip": "Add this project to the active settings.json",
  "toolbar.add_project_ok":  "Project added to settings.json.",
  "toolbar.sync_versions":   "Sync to highest",
  "toolbar.sync_versions_tip": "Set all visible projects to the highest version among them",
  "settings.title":         "Settings",
  "settings.body":          "settings.json has been opened in the editor.\n\nClick OK after saving to reload the settings.",
  "info.title":             "About VerBump",
  "info.language":          "Language: {0}",
  "info.description":       "Version file manager for Windows developers.\nFree \u0026 open source \u2014 MIT License.",
  "info.sponsor":           "\u2764  Sponsor this project on GitHub",
  "info.report":            "\u2709  Report an issue",
  "info.source":            "\u2325  View source on GitHub",
  "settings.created":       "settings.json created: {0}\nPlease enter your paths.",
  "error.json":             "JSON error: {0}",
  "error.save":             "Save error: {0}",
  "error.nofiles":          "No VERSION files found.\nSettings file: {0}\n\nOpen settings?",
  "error.bump_unavailable": "⚠ Ctrl+{0} not available for scheme \"{1}\"",
  "status.scheme":          "Scheme: {0}",
  "status.shortcut":        "Ctrl+{0}={1}",
  "status.backup_on":       "Backup: [X]",
  "status.backup_off":      "Backup: [ ]",
  "status.ok":              "VERSION is up to date.",
  "project.unnamed":        "Unnamed",
  "editor.title":           "Choose editor",
  "editor.prompt":          "Command or path to editor (e.g. code, notepad++, gedit):",
  "editor.error":           "Could not start editor: {0}",
  "menu.file":              "File",
  "menu.edit_settings":     "Settings",
  "menu.load_settings":     "Open Settings File",
  "menu.load_version":      "Open VERSION File",
  "menu.exit":              "Exit",
  "menu.edit":              "Edit",
  "menu.undo":              "Undo",
  "menu.view":              "View",
  "menu.show_stale":        "Show outdated",
  "menu.show_current":      "Show current",
  "menu.about":             "About VerBump",
  "menu.add_favorite":      "\u2605 Save as Favorite",
  "menu.remove_favorite":   "(\u2715) Remove from Favorites",
  "menu.add_version_fav":   "\u2605 Add to VERSION Favorites",
  "menu.remove_version_fav":"(\u2715) Remove from VERSION Favorites"
}

""",
        _ => null
    };
}
